- id: ast-checks
  name: Python AST checks (grouped)
  description: Run multiple AST-based checks in a single pass for improved performance
  entry: python -m pre_commit_hooks.ast_checks
  language: python
  types: [python]

- id: fix-misplaced-comments
  name: Fix misplaced comments
  description: Move trailing comments on closing brackets to expression lines
  entry: python -m pre_commit_hooks.fix_misplaced_comments
  language: python
  types: [python]
  args: [--fix]
